config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             controllers: {
                 sessions: 'users/sessions',
                 registrations: 'users/registrations'
             }

  root 'users#index'
  # resources :posts do
  #   resources :comments
  # end

  namespace :api do
    namespace :v1 do
      resources :posts
      get 'posts/:post_id/comments/' , to: 'posts#comments_for_post'
      post 'posts/:post_id/comments/', to: 'posts#create_comment'
    end
  end

  get '/users', to: 'users#index'
  get '/users/:id', to: 'users#show', as: 'user'

  delete '/users/:user_id/posts/:id', to: 'posts#destroy', as: 'delete_user_post'

  get '/users/:user_id/posts/new', to: 'posts#new', as: 'new_user_post'
  post '/users/:user_id/posts', to: 'posts#create', as: 'user_posts_create'

  delete '/users/:user_id/posts/:post_id/comments/:comment_id', to: 'comments#destroy', as: 'delete_user_post_comment'
  get '/users/:user_id/posts/:post_id/comments/new', to: 'comments#new', as: 'new_user_post_comment'
  post '/users/:user_id/posts/:post_id/comments', to: 'comments#create', as: 'user_post_comments'

  post '/user/:user_id/posts/:post_id/likes', to: 'likes#create', as: 'user_post_likes'

  get '/user/:user_id/posts', to: 'posts#index', as: 'user_posts'
  get '/user/:user_id/posts/:id', to: 'posts#show', as: 'user_post'
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: :author_id
  belongs_to :post

  validates :text, presence: true

  after_save :update_comments_counter

  private

  def update_comments_counter
    post.update(comments_counter: post.comments.count)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_user_and_post
  load_and_authorize_resource

  def new
    @comment = Comment.new
  end

  def create
    @comment = @post.comments.build(comment_params)
    @comment.author = current_user

    if @comment.save
      redirect_to user_post_path(@user, @post), notice: 'Comment was successfully created.'
    else
      render :new
    end
  end

  def destroy
    @comment = @post.comments.find(params[:comment_id])
    if @comment.destroy
      flash[:notice] = 'Comment deleted!'
    else
      flash[:alert] = 'Failed to delete comment!'
    end
    redirect_to user_post_path(@user, @post)
  end

  private

  def find_user_and_post
    @user = User.where(id: params[:user_id]).first
    @post = Post.where(id: params[:post_id]).first
  end

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/new.html.erb
<h2>New Comment</h2>
<% if @comment.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

    <ul>
    <% @comment.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: [@user, @post, Comment.new], url: user_post_comments_path(@user, @post), class: 'comment-form') do |form| %>
  <div class="field">
    <%= form.label :text, "Comment" %>
    <%= form.text_area :text, rows: 4 %>
  </div>

  <div class="actions">
    <%= form.submit 'Create Comment', class: 'button' %>
  </div>
<% end %>

<%= link_to 'Back', user_post_path(@user, @post), class: 'button' %>