config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             controllers: {
                 sessions: 'users/sessions',
                 registrations: 'users/registrations'
             }

  root 'users#index'
  # resources :posts do
  #   resources :comments
  # end

  namespace :api do
    namespace :v1 do
      resources :posts
      get 'posts/:post_id/comments/' , to: 'posts#comments_for_post'
      post 'posts/:post_id/comments/', to: 'posts#create_comment'
    end
  end

  get '/users', to: 'users#index'
  get '/users/:id', to: 'users#show', as: 'user'

  delete '/users/:user_id/posts/:id', to: 'posts#destroy', as: 'delete_user_post'

  get '/users/:user_id/posts/new', to: 'posts#new', as: 'new_user_post'
  post '/users/:user_id/posts', to: 'posts#create', as: 'user_posts_create'

  delete '/users/:user_id/posts/:post_id/comments/:comment_id', to: 'comments#destroy', as: 'delete_user_post_comment'
  get '/users/:user_id/posts/:post_id/comments/new', to: 'comments#new', as: 'new_user_post_comment'
  post '/users/:user_id/posts/:post_id/comments', to: 'comments#create', as: 'user_post_comments'

  post '/user/:user_id/posts/:post_id/likes', to: 'likes#create', as: 'user_post_likes'

  get '/user/:user_id/posts', to: 'posts#index', as: 'user_posts'
  get '/user/:user_id/posts/:id', to: 'posts#show', as: 'user_post'
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: :author_id
  has_many :comments
  has_many :likes

  validates :title, presence: true, length: { maximum: 250 }
  validates :content, presence: true
  validates :comments_counter, :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  after_save :update_post_counter

  # Public Methods
  def five_most_recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  private

  def update_post_counter
    author.update(post_counter: author.posts.count)
  end
end

app/controllers/api/v1/post_controller.rb
class Api::V1::PostsController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :authenticate_user!

  def index
    @posts = current_user.posts.includes(:comments, :likes)
    render json: @posts
  end

  def comments_for_post
    post = Post.find(params[:post_id])
    comments = post.comments
    render json: comments
  end

  def create_comment
    comment = Comment.new(post_id: params[:post_id], text: params[:comment], author_id: current_user.id)
    if comment.save
      render json: comment
    else
      render json: { error: 'Error al crear el comentario' }
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_user
  load_and_authorize_resource # Carga y autoriza automáticamente los recursos

  def index
    @posts = @user.posts.includes(:comments, :likes).page(params[:page]).per(3)
  end

  def create
    @post = @user.posts.build(post_params)
    if @post.save
      redirect_to user_post_path(@user, @post), notice: 'Post was successfully created.'
    else
      flash.now[:alert] = 'Post creation failed!'
      render :new
    end
  end

  def destroy
    @post = @user.posts.find(params[:id])
    @post.likes.destroy_all
    @post.comments.destroy_all
    if @post.destroy
      flash[:notice] = 'Post deleted!'
      redirect_to user_posts_path(@user)
    else
      flash[:alert] = 'Failed to delete post!'
      redirect_to user_post_path(@user)
    end
  end

  def show
    @post = @user.posts.find_by(id: params[:id])
    # @comments = @post.comments
    if @post
      @next_post = @user.posts.where('id > ?', @post.id).first
      @prev_post = @user.posts.where('id < ?', @post.id).last
    else
      flash[:alert] = 'Post not found'
      redirect_to user_posts_path(@user)
    end
  end

  def new
    @post = @user.posts.build
  end

  private

  def find_user
    @user = User.find(params[:user_id])
  end

  def post_params
    params.require(:post).permit(:title, :content)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/index.html.erb
<h1>All Posts</h1>
<div>
  <div class="user-card flex">
    <div class="user-image border">
      <img src="<%= @user.photo %>" alt="<%= @user.name %>'s photo" width="100%" heigth="100%">
    </div>
    <div class="user-info border">
      <h2><%= @user.name %></h2>
      <p class="posts-number">Number of posts: <%= @user.posts.count %></p>
    </div>
  </div>
</div>

<div>
<% if @user == current_user or current_user.admin? %>
  <%= link_to 'New Post', new_user_post_path(@user), class: 'button' %>
  <% end %>
  <ul>
    <% @posts.each do |post| %>
      <li>
        <div id="post-<%= post.id %>" class="user-card left">
        <h3 data-id="<%= post.id %>"><%= link_to post.title, user_post_path(@user, post) %></h3>

          <br>
          <p><%= post.content %></p>
          <div class="right">
            <span class="span-post">Comments: <%= post.comments.count %></span>
            <span class="span-post" data-target="likes_count">Likes: <%= post.likes.count %></span>

          </div>
        </div>
        <div id="comments-for-post-<%= post.id %>" class="user-card left">
  <ul>
    <h5>All the Comments:</h5>
    <br>
    <% post.five_most_recent_comments.each do |comment| %>
    <li><%= comment.author.name %>: <%= comment.text %></li>
    <% end %>
  </ul>
</div>
      </li>
    <% end %>
  </ul>
</div>

<%= paginate @posts, param_name: 'page', class: 'button' %>

app/views/posts/new.html.erb
<h2>New Post</h2>
<% if @post.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

    <ul>
    <% @post.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: [@user, @post], url: user_posts_create_path(@user), class: 'post-form') do |form| %>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit 'Create Post', class: 'button' %>
  </div>
<% end %>

<%= link_to 'Back', user_posts_path(@user), class: 'button' %>

app/views/posts/show.html.erb
<h2>Total Comments</h2>
<div>
  <div class="user-card left">
    <h3><%= @post.title %> by <%= @user.name %></h3>
    <div class="right">
      <span class="span-post">Comments: <%= @post.comments.count %></span>
      <span class="span-post" data-target="likes_count">Likes: <%= @post.likes.count %></span>
      <%= button_to "Like", user_post_likes_path(@user, @post), method: :post, class: "button", remote: true %>
    </div>
    <br>
    <p><%= @post.content %></p>
  </div>
  <div class="user-card left">
    <ul>
      <h5>All the Comments:</h5>
      <br>
      <% @post.comments.each do |comment| %>
        <li><%= comment.author.name %>: <%= comment.text %></li>
        <% if comment.author_id == current_user.id or current_user.admin? %>
        <%= button_to "Delete", delete_user_post_comment_path(@user, @post, comment), method: :delete, class: "button top" %>
      <% end %>
      <% end %>
    </ul>
  </div>
</div>

<%= link_to 'New Comment', new_user_post_comment_path(@user, @post), class: 'button top' %>

<% if @prev_post.present? %>
  <%= button_to "Previous Post", user_post_path(@user, @prev_post), method: :get, class: "button top" %>
<% end %>

<% if @next_post.present? %>
  <%= button_to "Next Post", user_post_path(@user, @next_post), method: :get, class: "button top" %>
<% end %>

<% if can? :destroy, @post %>
  <%= button_to "Delete the Post", delete_user_post_path(@user, @post), method: :delete, class: "button top" %>
<% end %>